# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path
from PyInstaller.utils.hooks import collect_all, copy_metadata

src_dir = Path('src').resolve()

# Collect all submodules/binaries/data from major ML packages
tf_data, tf_bin, tf_hidden = collect_all('transformers')
diff_data, diff_bin, diff_hidden = collect_all('diffusers')
hf_data, hf_bin, hf_hidden = collect_all('huggingface_hub')
acc_data, acc_bin, acc_hidden = collect_all('accelerate')
sf_data, sf_bin, sf_hidden = collect_all('safetensors')
cert_data, cert_bin, cert_hidden = collect_all('certifi')

a = Analysis(
    [str(src_dir / 'picture_aliver' / 'desktop.py')],
    pathex=[str(src_dir)],
    binaries=[
        (str(Path("E:/Python313/DLLs/zlib1.dll")), '.'),
        (str(Path("E:/Python313/vcruntime140.dll")), '.'),
    ] + tf_bin + diff_bin + hf_bin + acc_bin + sf_bin + cert_bin,
    datas=copy_metadata('requests') + copy_metadata('filelock') + [
        (str(src_dir / 'picture_aliver'), 'picture_aliver'),
        (str(src_dir / 'core'), 'core'),
        (str(src_dir / 'modules'), 'modules'),
        (str(src_dir / 'utils'), 'utils'),
        ('configs', 'configs'),
    ] + tf_data + diff_data + hf_data + acc_data + sf_data + cert_data,
    hiddenimports=[
        # torch & friends
        'torch._C',
        'torch.storage',
        'torch.distributions',
        'torch.jit',
        'torch.autograd',
        'torch.utils.data',
        'torch.backends.cuda',
        'torch.backends.mps',
        'torch.backends.mkldnn',
        'torch.nn',
        'torch.nn.functional',
        'torch.optim',
        'torch.cuda',
        'torch.cuda.comm',
        'torch.cuda.streams',
        'torch.version',
        # our project
        'core',
        'core.model_manager',
        'core.model_registry',
        'core.model_loader',
        'core.config',
        'core.device',
        'core.pipeline',
        'core.debug',
        'core.polaris_pipeline',
        'core.lynx_pipeline',
        'modules.depth',
        'modules.depth.depth_estimator',
        'modules.depth.types',
        'modules.generation',
        'modules.generation.artifact_reducer',
        'modules.generation.artifact_reduction',
        'modules.generation.content_analyzer',
        'modules.generation.controlnet_guidance',
        'modules.generation.depth_conditioning',
        'modules.generation.frame_interpolator',
        'modules.generation.furry_models',
        'modules.generation.latent_consistency',
        'modules.generation.optical_flow_stabilizer',
        'modules.generation.temporal_consistency',
        'modules.generation.types',
        'modules.generation.video_generator',
        'modules.motion',
        'modules.motion.camera_motion',
        'modules.motion.env_motion',
        'modules.motion.flow_estimator',
        'modules.motion.furry_motions',
        'modules.motion.generation',
        'modules.motion.motion_injector',
        'modules.motion.object_motion',
        'modules.motion.parallax',
        'modules.motion.physics_motion',
        'modules.motion.types',
        'modules.segmentation',
        'modules.segmentation.segmentor',
        'modules.segmentation.types',
        'utils',
        'utils.image_utils',
        'utils.logger',
        'utils.video_utils',
        'picture_aliver',
        'picture_aliver.experiences',
        'picture_aliver.cli',
        'picture_aliver.text_to_image',
        'picture_aliver.config_loader',
        'picture_aliver.exporter',
        'picture_aliver.gpu_optimization',
        'picture_aliver.image_loader',
        'picture_aliver.main',
        'picture_aliver.motion_generator',
        'picture_aliver.motion_prompt',
        'picture_aliver.quality_control',
        'picture_aliver.segmentation',
        'picture_aliver.stabilizer',
        'picture_aliver.video_generator',
        'picture_aliver.desktop',
        # Wan2.2 video diffusion
        'diffusers.pipelines.wan',
        'diffusers.models.transformers.transformer_wan',
        'diffusers.models.autoencoders.vae',
        'tkinterdnd2',
        'tkinterdnd2.TkinterDnD',
        # common dependencies
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'cv2',
        'numpy',
        'yaml',
        'safetensors',
        'huggingface_hub',
        'huggingface_hub.utils',
        'accelerate',
        'accelerate.utils',
        'torch.distributed.nn',
    ] + tf_hidden + diff_hidden + hf_hidden + acc_hidden + sf_hidden + cert_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'notebook',
        'ipython',
        'jupyter',
        'test',
        'tests',
        'tensorboard',
        'tensorflow',
        'PIL._avif',
        'PIL._heif',
        'torch.utils.benchmark',
        'onnx',
        'onnxruntime',
    ],
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    [],
    name='PicAliver',
    debug=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='PicAliver',
)
